server:
  port: 9527
spring:
  application:
    name: bambooCloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  prefix: /bamboo
  ignored-services: "*"
  routes:
    user.serviceId: "BAMBOOCLOUD-USER"
    user.path: /myUser/**

info:
  app.name: bambooCloud
  company.name: 汉乾
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

management:
  endpoints:
    web:
      exposure:
        include: '*'

